version: '3.12.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://localhost:27017
      - GitHub_client-secret=deae0508a68030fb5b81dc6050056fa1606f1bdb
      - GitHub_client-id=Ov23liuMLsSZ9Sk0p1p0
      - secret-key=mypass1337
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      -mongo_data:/data/db

volumes:
  mongo_data: